services:
  db:
    image: postgres:15-alpine
    container_name: auth_service
    restart: always
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
